import Foundation

enum L10n {
    static func text(_ key: String) -> String {
        let language = AppSettings.shared.resolvedLanguage
        return table[key]?[language] ?? table[key]?[.english] ?? key
    }

    private static let table: [String: [AppLanguage: String]] = [
        "settings.title": [.english: "Acrylic Calendar Settings", .russian: "Параметры Acrylic Calendar", .ukrainian: "Параметри Acrylic Calendar", .german: "Acrylic-Calendar-Einstellungen", .french: "Paramètres d’Acrylic Calendar", .japanese: "Acrylic Calendar 設定", .tatar: "Acrylic Calendar көйләүләре"],
        "settings": [.english: "Settings", .russian: "Настройки", .ukrainian: "Налаштування", .german: "Einstellungen", .french: "Réglages", .japanese: "設定", .tatar: "Көйләүләр"],
        "settings.ellipsis": [.english: "Settings...", .russian: "Настройки...", .ukrainian: "Налаштування...", .german: "Einstellungen...", .french: "Réglages...", .japanese: "設定...", .tatar: "Көйләүләр..."],
        "openCalendarPanel": [.english: "Open Calendar Panel", .russian: "Открыть панель календаря", .ukrainian: "Відкрити панель календаря", .german: "Kalenderleiste öffnen", .french: "Ouvrir le panneau du calendrier", .japanese: "カレンダーパネルを開く", .tatar: "Календарь панелен ачу"],
        "openFullCalendar": [.english: "Open Full Calendar", .russian: "Открыть полный календарь", .ukrainian: "Відкрити повний календар", .german: "Vollständigen Kalender öffnen", .french: "Ouvrir le calendrier complet", .japanese: "フルカレンダーを開く", .tatar: "Тулы календарьны ачу"],
        "quit": [.english: "Quit Fluent Calendar", .russian: "Выйти из Fluent Calendar", .ukrainian: "Вийти з Fluent Calendar", .german: "Fluent Calendar beenden", .french: "Quitter Fluent Calendar", .japanese: "Fluent Calendarを終了", .tatar: "Fluent Calendar'дан чыгу"],
        "calendar": [.english: "Calendar", .russian: "Календарь", .ukrainian: "Календар", .german: "Kalender", .french: "Calendrier", .japanese: "カレンダー", .tatar: "Календарь"],
        "appearance": [.english: "Appearance", .russian: "Оформление", .ukrainian: "Оформлення", .german: "Darstellung", .french: "Apparence", .japanese: "外観", .tatar: "Күренеш"],
        "theme": [.english: "Theme", .russian: "Тема", .ukrainian: "Тема", .german: "Design", .french: "Thème", .japanese: "テーマ", .tatar: "Тема"],
        "theme.system": [.english: "Use macOS appearance", .russian: "Как в macOS", .ukrainian: "Як у macOS", .german: "macOS-Darstellung verwenden", .french: "Utiliser l’apparence macOS", .japanese: "macOSの外観を使用", .tatar: "macOS күренешен куллану"],
        "theme.light": [.english: "Light mode", .russian: "Светлая тема", .ukrainian: "Світла тема", .german: "Hell", .french: "Mode clair", .japanese: "ライトモード", .tatar: "Якты тема"],
        "theme.dark": [.english: "Dark mode", .russian: "Темная тема", .ukrainian: "Темна тема", .german: "Dunkel", .french: "Mode sombre", .japanese: "ダークモード", .tatar: "Караңгы тема"],
        "language": [.english: "Language", .russian: "Язык", .ukrainian: "Мова", .german: "Sprache", .french: "Langue", .japanese: "言語", .tatar: "Тел"],
        "language.system": [.english: "System", .russian: "Системный", .ukrainian: "Системна", .german: "System", .french: "Système", .japanese: "システム", .tatar: "Система"],
        "showDate": [.english: "Show date", .russian: "Показывать дату", .ukrainian: "Показувати дату", .german: "Datum anzeigen", .french: "Afficher la date", .japanese: "日付を表示", .tatar: "Датаны күрсәтү"],
        "date.whenSpaceAllows": [.english: "When space allows", .russian: "Если хватает места", .ukrainian: "Коли вистачає місця", .german: "Wenn Platz ist", .french: "Si l’espace le permet", .japanese: "空きがある場合", .tatar: "Урын җитсә"],
        "date.always": [.english: "Always", .russian: "Всегда", .ukrainian: "Завжди", .german: "Immer", .french: "Toujours", .japanese: "常に", .tatar: "Һәрвакыт"],
        "date.never": [.english: "Never", .russian: "Никогда", .ukrainian: "Ніколи", .german: "Nie", .french: "Jamais", .japanese: "表示しない", .tatar: "Беркайчан"],
        "showDayOfWeek": [.english: "Show day of week", .russian: "Показывать день недели", .ukrainian: "Показувати день тижня", .german: "Wochentag anzeigen", .french: "Afficher le jour de la semaine", .japanese: "曜日を表示", .tatar: "Атна көнен күрсәтү"],
        "hourCycle": [.english: "Hour cycle", .russian: "Формат времени", .ukrainian: "Формат часу", .german: "Zeitformat", .french: "Format horaire", .japanese: "時刻形式", .tatar: "Вакыт форматы"],
        "hour.system": [.english: "Use system setting", .russian: "Как в системе", .ukrainian: "Як у системі", .german: "Systemeinstellung verwenden", .french: "Utiliser le réglage système", .japanese: "システム設定を使用", .tatar: "Система көйләвен куллану"],
        "hour.twelve": [.english: "12-hour time", .russian: "12-часовой формат", .ukrainian: "12-годинний формат", .german: "12-Stunden-Format", .french: "Format 12 heures", .japanese: "12時間表示", .tatar: "12 сәгать форматы"],
        "hour.twentyFour": [.english: "24-hour time", .russian: "24-часовой формат", .ukrainian: "24-годинний формат", .german: "24-Stunden-Format", .french: "Format 24 heures", .japanese: "24時間表示", .tatar: "24 сәгать форматы"],
        "showSeconds": [.english: "Show seconds", .russian: "Показывать секунды", .ukrainian: "Показувати секунди", .german: "Sekunden anzeigen", .french: "Afficher les secondes", .japanese: "秒を表示", .tatar: "Секундларны күрсәтү"],
        "about": [.english: "About Acrylic calendar", .russian: "О программе Acrylic calendar", .ukrainian: "Про Acrylic calendar", .german: "Über Acrylic calendar", .french: "À propos d’Acrylic calendar", .japanese: "Acrylic calendar について", .tatar: "Acrylic calendar турында"],
        "useAccent": [.english: "Use macOS accent color", .russian: "Использовать акцент macOS", .ukrainian: "Використовувати акцент macOS", .german: "macOS-Akzentfarbe verwenden", .french: "Utiliser la couleur d’accent macOS", .japanese: "macOSのアクセントカラーを使用", .tatar: "macOS акцент төсен куллану"],
        "accent": [.english: "Accent", .russian: "Акцент", .ukrainian: "Акцент", .german: "Akzent", .french: "Accent", .japanese: "アクセント", .tatar: "Акцент"],
        "macosClock": [.english: "macOS Clock", .russian: "Часы macOS", .ukrainian: "Годинник macOS", .german: "macOS-Uhr", .french: "Horloge macOS", .japanese: "macOSの時計", .tatar: "macOS сәгате"],
        "clockHelp": [.english: "macOS does not provide a public API for hiding the built-in menu bar clock. Open System Settings and hide it manually if the option is available on this Tahoe build.", .russian: "macOS не предоставляет публичный API для скрытия встроенных часов в строке меню. Откройте Системные настройки и отключите их вручную, если такая опция доступна в этой сборке Tahoe.", .ukrainian: "macOS не надає публічного API для приховування вбудованого годинника в рядку меню. Відкрийте Системні параметри й вимкніть його вручну, якщо ця опція доступна в цій збірці Tahoe.", .german: "macOS stellt keine öffentliche API bereit, um die integrierte Menüleistenuhr auszublenden. Öffne die Systemeinstellungen und blende sie manuell aus, sofern diese Option in diesem Tahoe-Build verfügbar ist.", .french: "macOS ne fournit pas d’API publique pour masquer l’horloge intégrée de la barre des menus. Ouvrez Réglages Système et masquez-la manuellement si l’option est disponible dans cette version de Tahoe.", .japanese: "macOSにはメニューバー標準時計を非表示にする公開APIがありません。このTahoeビルドで利用できる場合は、システム設定で手動で非表示にしてください。", .tatar: "macOS меню юлындагы стандарт сәгатьне яшерү өчен ачык API бирми. Бу Tahoe җыелмасында мөмкин булса, Система көйләүләрен ачып аны кулдан яшерегез."],
        "openClockSettings": [.english: "Open Clock Settings", .russian: "Открыть настройки часов", .ukrainian: "Відкрити налаштування годинника", .german: "Uhreinstellungen öffnen", .french: "Ouvrir les réglages de l’horloge", .japanese: "時計設定を開く", .tatar: "Сәгать көйләүләрен ачу"],
        "launchAtLogin": [.english: "Add to login items", .russian: "Добавить в автозапуск", .ukrainian: "Додати в автозапуск", .german: "Zu Anmeldeobjekten hinzufügen", .french: "Ajouter à l’ouverture de session", .japanese: "ログイン項目に追加", .tatar: "Автоэшләтүгә өстәү"],
        "launchAtLoginError": [.english: "Launch at login could not be changed", .russian: "Не удалось изменить запуск при входе", .ukrainian: "Не вдалося змінити запуск під час входу", .german: "Start beim Anmelden konnte nicht geändert werden", .french: "Impossible de modifier le lancement à l’ouverture de session", .japanese: "ログイン時の起動を変更できませんでした", .tatar: "Кергәндә эшләтүне үзгәртеп булмады"],
        "today": [.english: "Today", .russian: "Сегодня", .ukrainian: "Сьогодні", .german: "Heute", .french: "Aujourd’hui", .japanese: "今日", .tatar: "Бүген"],
        "day": [.english: "Day", .russian: "День", .ukrainian: "День", .german: "Tag", .french: "Jour", .japanese: "日", .tatar: "Көн"],
        "week": [.english: "Week", .russian: "Неделя", .ukrainian: "Тиждень", .german: "Woche", .french: "Semaine", .japanese: "週", .tatar: "Атна"],
        "month": [.english: "Month", .russian: "Месяц", .ukrainian: "Місяць", .german: "Monat", .french: "Mois", .japanese: "月", .tatar: "Ай"],
        "year": [.english: "Year", .russian: "Год", .ukrainian: "Рік", .german: "Jahr", .french: "Année", .japanese: "年", .tatar: "Ел"],
        "newEvent": [.english: "New event", .russian: "Новое событие", .ukrainian: "Нова подія", .german: "Neuer Termin", .french: "Nouvel événement", .japanese: "新しい予定", .tatar: "Яңа вакыйга"],
        "addAnotherEvent": [.english: "Add another event", .russian: "Добавить еще событие", .ukrainian: "Додати ще подію", .german: "Weiteren Termin hinzufügen", .french: "Ajouter un autre événement", .japanese: "別の予定を追加", .tatar: "Тагын вакыйга өстәү"],
        "addEventReminder": [.english: "Add an event or reminder", .russian: "Добавить событие или напоминание", .ukrainian: "Додати подію або нагадування", .german: "Termin oder Erinnerung hinzufügen", .french: "Ajouter un événement ou un rappel", .japanese: "予定またはリマインダーを追加", .tatar: "Вакыйга яки искәртү өстәү"],
        "noEvents": [.english: "No events", .russian: "Нет событий", .ukrainian: "Немає подій", .german: "Keine Termine", .french: "Aucun événement", .japanese: "予定なし", .tatar: "Вакыйгалар юк"],
        "noEventsForDay": [.english: "No events for this day.", .russian: "На этот день событий нет.", .ukrainian: "На цей день подій немає.", .german: "Keine Termine an diesem Tag.", .french: "Aucun événement pour ce jour.", .japanese: "この日の予定はありません。", .tatar: "Бу көнгә вакыйгалар юк."],
        "allDay": [.english: "All day", .russian: "Весь день", .ukrainian: "Увесь день", .german: "Ganztägig", .french: "Toute la journée", .japanese: "終日", .tatar: "Көне буе"],
        "more": [.english: "more", .russian: "еще", .ukrainian: "ще", .german: "weitere", .french: "de plus", .japanese: "件以上", .tatar: "тагын"],
        "loadingEvents": [.english: "Loading events...", .russian: "Загрузка событий...", .ukrainian: "Завантаження подій...", .german: "Termine werden geladen...", .french: "Chargement des événements...", .japanese: "予定を読み込み中...", .tatar: "Вакыйгалар йөкләнә..."],
        "createEventOnSelectedDay": [.english: "Create an event on the selected day.", .russian: "Создать событие на выбранный день.", .ukrainian: "Створити подію на вибраний день.", .german: "Termin am ausgewählten Tag erstellen.", .french: "Créer un événement le jour sélectionné.", .japanese: "選択した日に予定を作成します。", .tatar: "Сайланган көнгә вакыйга ясау."],
        "save": [.english: "Save", .russian: "Сохранить", .ukrainian: "Зберегти", .german: "Speichern", .french: "Enregistrer", .japanese: "保存", .tatar: "Саклау"],
        "cancel": [.english: "Cancel", .russian: "Отмена", .ukrainian: "Скасувати", .german: "Abbrechen", .french: "Annuler", .japanese: "キャンセル", .tatar: "Баш тарту"],
        "eventName": [.english: "Event name", .russian: "Название события", .ukrainian: "Назва події", .german: "Terminname", .french: "Nom de l’événement", .japanese: "予定名", .tatar: "Вакыйга исеме"],
        "location": [.english: "Location", .russian: "Место", .ukrainian: "Місце", .german: "Ort", .french: "Lieu", .japanese: "場所", .tatar: "Урын"],
        "addLocation": [.english: "Add a location", .russian: "Добавить место", .ukrainian: "Додати місце", .german: "Ort hinzufügen", .french: "Ajouter un lieu", .japanese: "場所を追加", .tatar: "Урын өстәү"],
        "moreDetails": [.english: "More details", .russian: "Подробнее", .ukrainian: "Докладніше", .german: "Weitere Details", .french: "Plus de détails", .japanese: "詳細", .tatar: "Тулырак"],
        "to": [.english: "to", .russian: "до", .ukrainian: "до", .german: "bis", .french: "à", .japanese: "から", .tatar: "кадәр"],
        "noReminder": [.english: "No reminder", .russian: "Без напоминания", .ukrainian: "Без нагадування", .german: "Keine Erinnerung", .french: "Aucun rappel", .japanese: "リマインダーなし", .tatar: "Искәртүсез"],
        "minutes15": [.english: "15 minutes", .russian: "15 минут", .ukrainian: "15 хвилин", .german: "15 Minuten", .french: "15 minutes", .japanese: "15分", .tatar: "15 минут"],
        "minutes30": [.english: "30 minutes", .russian: "30 минут", .ukrainian: "30 хвилин", .german: "30 Minuten", .french: "30 minutes", .japanese: "30分", .tatar: "30 минут"],
        "hour1": [.english: "1 hour", .russian: "1 час", .ukrainian: "1 година", .german: "1 Stunde", .french: "1 heure", .japanese: "1時間", .tatar: "1 сәгать"],
        "day1": [.english: "1 day", .russian: "1 день", .ukrainian: "1 день", .german: "1 Tag", .french: "1 jour", .japanese: "1日", .tatar: "1 көн"],
        "eventSaveError": [.english: "Event could not be saved", .russian: "Не удалось сохранить событие", .ukrainian: "Не вдалося зберегти подію", .german: "Termin konnte nicht gespeichert werden", .french: "Impossible d’enregistrer l’événement", .japanese: "予定を保存できませんでした", .tatar: "Вакыйганы саклап булмады"]
    ]
}
